# Applying Advanced Transformations (Core)

## Task:

- Your task is two-fold:

1. Clean the files and combine them into one final DataFrame.

      - This dataframe should have the following columns:
           - Hero (Just the name of the Hero)
           - Publisher
           - Gender
           - Eye color
           - Race
           - Hair color
           - Height (numeric)
           - Skin color
           - Alignment
           - Weight (numeric)
           - Plus, one-hot-encoded columns for every power that appears in the dataset. E.g.:
                - Agility
                - Flight
                - Superspeed
                - etc.

 Hint: There is a space in "100 kg" or "52.5 cm"

    
2. Use your combined DataFrame to answer the following questions.

    - Compare the average weight of super powers who have Super Speed to those who do not.
    - What is the average height of heroes for each publisher?

## Imports

In [43]:
import numpy as np
import pandas as pd
import json

In [44]:
info = pd.read_csv('https://docs.google.com/spreadsheets/d/e/2PACX-1vS1ZstYLwFgwhZnqDsPjtnlHYhJp_cmW55J8JD5mym0seRsaem3px7QBtuFF0LiI7z1PLCkVKAkdO7J/pub?output=csv')
powers = pd.read_csv('https://docs.google.com/spreadsheets/d/e/2PACX-1vSzdWOBaXOoz52vPmCFV5idNlDBohLY1Lsbc1IfZIZQ7cV_aNB2wYBfhF49uE1TaO1B5MQCGWiNrFfd/pub?output=csv')

In [45]:
info.head()

,Hero|Publisher,Gender,Race,Alignment,Hair color,Eye color,Skin color,Measurements
0,A-Bomb|Marvel Comics,Male,Human,good,No Hair,yellow,Unknown,"{'Height': '203.0 cm', 'Weight': '441.0 kg'}"
1,Abe Sapien|Dark Horse Comics,Male,Icthyo Sapien,good,No Hair,blue,blue,"{'Height': '191.0 cm', 'Weight': '65.0 kg'}"
2,Abin Sur|DC Comics,Male,Ungaran,good,No Hair,blue,red,"{'Height': '185.0 cm', 'Weight': '90.0 kg'}"
3,Abomination|Marvel Comics,Male,Human / Radiation,bad,No Hair,green,Unknown,"{'Height': '203.0 cm', 'Weight': '441.0 kg'}"
4,Absorbing Man|Marvel Comics,Male,Human,bad,No Hair,blue,Unknown,"{'Height': '193.0 cm', 'Weight': '122.0 kg'}"

In [46]:
powers.head()

    hero_names                                             Powers
0      3-D Man         Agility,Super Strength,Stamina,Super Speed
1       A-Bomb  Accelerated Healing,Durability,Longevity,Super...
2   Abe Sapien  Agility,Accelerated Healing,Cold Resistance,Du...
3     Abin Sur                                 Lantern Power Ring
4  Abomination  Accelerated Healing,Intelligence,Super Strengt...

In [47]:
print(info.info())
print(powers.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 463 entries, 0 to 462
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Hero|Publisher  463 non-null    object
 1   Gender          463 non-null    object
 2   Race            463 non-null    object
 3   Alignment       463 non-null    object
 4   Hair color      463 non-null    object
 5   Eye color       463 non-null    object
 6   Skin color      463 non-null    object
 7   Measurements    463 non-null    object
dtypes: object(8)
memory usage: 29.1+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 667 entries, 0 to 666
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   hero_names  667 non-null    object
 1   Powers      667 non-null    object
dtypes: object(2)
memory usage: 10.5+ KB
None

In [48]:
info['Hero|Publisher'].head(3)

0            A-Bomb|Marvel Comics
1    Abe Sapien|Dark Horse Comics
2              Abin Sur|DC Comics
Name: Hero|Publisher, dtype: object

In [49]:
info['Hero|Publisher'].str.split('|', expand=True)

                   0                  1
0             A-Bomb      Marvel Comics
1         Abe Sapien  Dark Horse Comics
2           Abin Sur          DC Comics
3        Abomination      Marvel Comics
4      Absorbing Man      Marvel Comics
..               ...                ...
458     Yellowjacket      Marvel Comics
459  Yellowjacket II      Marvel Comics
460             Yoda       George Lucas
461          Zatanna          DC Comics
462             Zoom          DC Comics

[463 rows x 2 columns]

In [50]:
info[['Hero', 'Publisher']] = info['Hero|Publisher'].str.split('|', expand=True)
info.head(2)

,Hero|Publisher,Gender,Race,Alignment,Hair color,Eye color,Skin color,Measurements,Hero,Publisher
0,A-Bomb|Marvel Comics,Male,Human,good,No Hair,yellow,Unknown,"{'Height': '203.0 cm', 'Weight': '441.0 kg'}",A-Bomb,Marvel Comics
1,Abe Sapien|Dark Horse Comics,Male,Icthyo Sapien,good,No Hair,blue,blue,"{'Height': '191.0 cm', 'Weight': '65.0 kg'}",Abe Sapien,Dark Horse Comics

In [51]:
info= info.drop(columns=['Hero|Publisher'])
info.head(3)

,Gender,Race,Alignment,Hair color,Eye color,Skin color,Measurements,Hero,Publisher
0,Male,Human,good,No Hair,yellow,Unknown,"{'Height': '203.0 cm', 'Weight': '441.0 kg'}",A-Bomb,Marvel Comics
1,Male,Icthyo Sapien,good,No Hair,blue,blue,"{'Height': '191.0 cm', 'Weight': '65.0 kg'}",Abe Sapien,Dark Horse Comics
2,Male,Ungaran,good,No Hair,blue,red,"{'Height': '185.0 cm', 'Weight': '90.0 kg'}",Abin Sur,DC Comics

In [52]:
measure= info.loc[0, "Measurements"]
measure

"{'Height': '203.0 cm', 'Weight': '441.0 kg'}"

In [53]:
measure= measure.replace("'", '"')
measure

'{"Height": "203.0 cm", "Weight": "441.0 kg"}'

In [54]:
fixed_measure= json.loads(measure)
print(type(fixed_measure))
fixed_measure

<class 'dict'>

{'Height': '203.0 cm', 'Weight': '441.0 kg'}

In [55]:
info['Measurements']= info['Measurements'].str.replace("'",'"')

In [56]:
info['Measurements']= info['Measurements'].apply(json.loads)
info['Measurements'].head()

0    {'Height': '203.0 cm', 'Weight': '441.0 kg'}
1     {'Height': '191.0 cm', 'Weight': '65.0 kg'}
2     {'Height': '185.0 cm', 'Weight': '90.0 kg'}
3    {'Height': '203.0 cm', 'Weight': '441.0 kg'}
4    {'Height': '193.0 cm', 'Weight': '122.0 kg'}
Name: Measurements, dtype: object

In [57]:
ht_wt= info['Measurements'].apply(pd.Series)
ht_wt

       Height    Weight
0    203.0 cm  441.0 kg
1    191.0 cm   65.0 kg
2    185.0 cm   90.0 kg
3    203.0 cm  441.0 kg
4    193.0 cm  122.0 kg
..        ...       ...
458  183.0 cm   83.0 kg
459  165.0 cm   52.0 kg
460   66.0 cm   17.0 kg
461  170.0 cm   57.0 kg
462  185.0 cm   81.0 kg

[463 rows x 2 columns]

In [58]:
info = pd.concat((info, ht_wt), axis = 1)
info.head(2)

,Gender,Race,Alignment,Hair color,Eye color,Skin color,Measurements,Hero,Publisher,Height,Weight
0,Male,Human,good,No Hair,yellow,Unknown,"{'Height': '203.0 cm', 'Weight': '441.0 kg'}",A-Bomb,Marvel Comics,203.0 cm,441.0 kg
1,Male,Icthyo Sapien,good,No Hair,blue,blue,"{'Height': '191.0 cm', 'Weight': '65.0 kg'}",Abe Sapien,Dark Horse Comics,191.0 cm,65.0 kg

In [59]:
info= info.drop(columns= ['Measurements'])
info.head(1)

,Gender,Race,Alignment,Hair color,Eye color,Skin color,Hero,Publisher,Height,Weight
0,Male,Human,good,No Hair,yellow,Unknown,A-Bomb,Marvel Comics,203.0 cm,441.0 kg

In [60]:
powers.head()

    hero_names                                             Powers
0      3-D Man         Agility,Super Strength,Stamina,Super Speed
1       A-Bomb  Accelerated Healing,Durability,Longevity,Super...
2   Abe Sapien  Agility,Accelerated Healing,Cold Resistance,Du...
3     Abin Sur                                 Lantern Power Ring
4  Abomination  Accelerated Healing,Intelligence,Super Strengt...

In [35]:
powers.loc[1, 'Powers']

'Accelerated Healing,Durability,Longevity,Super Strength,Stamina,Camouflage,Self-Sustenance'

In [62]:
powers['powers_split']= powers['Powers'].str.replace("'",'"')

In [63]:
powers['powers_split'].value_counts()

Intelligence                                                                                                                                                                                                                                                         8
Durability,Super Strength                                                                                                                                                                                                                                            5
Agility,Stealth,Marksmanship,Weapons Master,Stamina                                                                                                                                                                                                                  4
Marksmanship                                                                                                                                                                                                                                                         4
Teleportation                                                                                                                                                                                                                                                        4
                                                                                                                                                                                                                                                                    ..
Accelerated Healing,Flight,Telepathy,Energy Blasts,Teleportation,Telekinesis,Astral Projection,Psionic Powers,Mind Blast,Regeneration,Illusions,Resurrection                                                                                                         1
Flight,Telepathy,Animal Oriented Powers,Gliding                                                                                                                                                                                                                      1
Accelerated Healing,Durability,Energy Absorption,Flight,Super Strength,Telepathy,Energy Blasts,Size Changing,Super Speed,Darkforce Manipulation,Enhanced Senses,Phasing,Invulnerability,Self-Sustenance,Gravity Control,Energy Manipulation,Time Travel,Illusions    1
Agility,Accelerated Healing,Super Strength,Super Speed,Animal Oriented Powers,Enhanced Senses,Jump,Reflexes,Natural Weapons                                                                                                                                          1
Super Speed,Intangibility,Time Travel,Time Manipulation                                                                                                                                                                                                              1
Name: powers_split, Length: 608, dtype: int64

In [65]:
exploded= powers.explode('powers_split')
exploded[['hero_names', 'Powers', 'powers_split']].head(20)

,hero_names,Powers,powers_split
0,3-D Man,"Agility,Super Strength,Stamina,Super Speed","Agility,Super Strength,Stamina,Super Speed"
1,A-Bomb,"Accelerated Healing,Durability,Longevity,Super...","Accelerated Healing,Durability,Longevity,Super..."
2,Abe Sapien,"Agility,Accelerated Healing,Cold Resistance,Du...","Agility,Accelerated Healing,Cold Resistance,Du..."
3,Abin Sur,Lantern Power Ring,Lantern Power Ring
4,Abomination,"Accelerated Healing,Intelligence,Super Strengt...","Accelerated Healing,Intelligence,Super Strengt..."
5,Abraxas,"Dimensional Awareness,Flight,Intelligence,Supe...","Dimensional Awareness,Flight,Intelligence,Supe..."
6,Absorbing Man,"Cold Resistance,Durability,Energy Absorption,S...","Cold Resistance,Durability,Energy Absorption,S..."
7,Adam Monroe,"Accelerated Healing,Immortality,Regeneration","Accelerated Healing,Immortality,Regeneration"
8,Adam Strange,"Durability,Stealth,Flight,Marksmanship,Weapons...","Durability,Stealth,Flight,Marksmanship,Weapons..."
9,Agent Bob,Stealth,Stealth
10,Agent Zero,"Energy Absorption,Longevity,Super Strength,Ene...","Energy Absorption,Longevity,Super Strength,Ene..."
11,Air-Walker,"Flight,Super Strength,Super Speed,Self-Sustena...","Flight,Super Strength,Super Speed,Self-Sustena..."
12,Ajax,"Agility,Super Strength,Super Speed,Heat Genera...","Agility,Super Strength,Super Speed,Heat Genera..."
13,Alan Scott,"Flight,Danger Sense,Intelligence,Telepathy,Ene...","Flight,Danger Sense,Intelligence,Telepathy,Ene..."
14,Alex Mercer,"Agility,Accelerated Healing,Stealth,Energy Abs...","Agility,Accelerated Healing,Stealth,Energy Abs..."
15,Alex Woolsly,Underwater breathing,Underwater breathing
16,Alien,"Agility,Cold Resistance,Durability,Stealth,Sup...","Agility,Cold Resistance,Durability,Stealth,Sup..."
17,Allan Quatermain,Marksmanship,Marksmanship
18,Amazo,"Agility,Lantern Power Ring,Durability,Flight,U...","Agility,Lantern Power Ring,Durability,Flight,U..."
19,Ammo,Weapons Master,Weapons Master